name: Setup Deno with cache
description: setup-deno with dependencies cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: deno-${{ github.job }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          deno-${{ github.job }}-${{ runner.os }}-
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Setup Node.js for dnt
      uses: actions/setup-node@v4
      with:
        node-version: 20
