name: Check GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-actions:
    timeout-minutes: 30
    name: Check GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Check Changed Files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            actions:
              - ".github/workflows/*.yml"
              - ".github/workflows/*.yaml"
      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        if: steps.filter.outputs.actions == 'true'
        with:
          aqua_version: v2.54.1
      - name: Linting
        if: steps.filter.outputs.actions == 'true'
        run: |
          shellcheck --version
          ghalint run
          actionlint -color
